name: Main Executable (SLES_015.14)
sha1: 7ADA563BBAB31CF95AFD9327E0762F0E35EDFCB6
options:
  basename: main
  target_path: rom/EUR/SLES_015.14
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/main
  src_path: src/main
  build_path: build/EUR
  # create_asm_dependencies: True

  ld_script_path: linkers/EUR/main.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".sdata", ".sbss", ".bss"]
  
  symbol_addrs_path:
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/rel.main.txt

  undefined_funcs_auto_path: linkers/EUR/undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/EUR/undefined_syms_auto.main.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

  ld_bss_is_noload: False
segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subalign: 4
    subsegments:
      - [0x800, rodata]
      - [0xF74, asm, main]
      - [0xB8FC, data]
  - [0x14800]
