name: The MAP2_S02 map overlay (MAP2_S02)
sha1: fd5ffe5979ebaec3ca654521ca70262bb79f21dd
options:
  basename: MAP2_S02.BIN
  target_path: assets/JAP2/VIN/MAP2_S02.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP2/maps/map2_s02
  src_path: src/maps/map2_s02
  build_path: build/JAP2

  ld_script_path: linkers/JAP2/maps/map2_s02.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP2/sym.main.txt
    - configs/JAP2/sym.bodyprog.txt
    - configs/JAP2/maps/sym.map2_s02.txt
  reloc_addrs_path:
    - configs/JAP2/maps/rel.map2_s02.txt

  undefined_funcs_auto_path: linkers/JAP2/maps/undefined_funcs_auto.map2_s02.txt
  undefined_syms_auto_path: linkers/JAP2/maps/undefined_syms_auto.map2_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map2_s02
    type: code
    start: 0
    vram: 0x800CBBD0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x32E4, asm, map2_s02]
      - [0x21464, data]
  - [0x27700]
