name: The MAP5_S03 map overlay (MAP5_S03)
sha1: 4842a024de340002253fcf8e1ab2fe42949dc0c5
options:
  basename: MAP5_S03.BIN
  target_path: assets/JAP2/VIN/MAP5_S03.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP2/maps/map5_s03
  src_path: src/maps/map5_s03
  build_path: build/JAP2

  ld_script_path: linkers/JAP2/maps/map5_s03.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP2/sym.main.txt
    - configs/JAP2/sym.bodyprog.txt
    - configs/JAP2/maps/sym.map5_s03.txt
  reloc_addrs_path:
    - configs/JAP2/maps/rel.map5_s03.txt

  undefined_funcs_auto_path: linkers/JAP2/maps/undefined_funcs_auto.map5_s03.txt
  undefined_syms_auto_path: linkers/JAP2/maps/undefined_syms_auto.map5_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map5_s03
    type: code
    start: 0
    vram: 0x800CBBD0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x2294, asm, map5_s03]
      - [0x9508, data]
  - [0xDB00]
