name: The MAP6_S04 map overlay (MAP6_S04)
sha1: a0045e0572494f3914b03bb841df791f3bffbedd
options:
  basename: MAP6_S04.BIN
  target_path: assets/JAP2/VIN/MAP6_S04.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP2/maps/map6_s04
  src_path: src/maps/map6_s04
  build_path: build/JAP2

  ld_script_path: linkers/JAP2/maps/map6_s04.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP2/sym.main.txt
    - configs/JAP2/sym.bodyprog.txt
    - configs/JAP2/maps/sym.map6_s04.txt
  reloc_addrs_path:
    - configs/JAP2/maps/rel.map6_s04.txt

  undefined_funcs_auto_path: linkers/JAP2/maps/undefined_funcs_auto.map6_s04.txt
  undefined_syms_auto_path: linkers/JAP2/maps/undefined_syms_auto.map6_s04.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map6_s04
    type: code
    start: 0
    vram: 0x800CBBD0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x3208, asm, map7_s03]
      - [0x1e5c0, data]
  - [0x24A00]
