name: Options screen overlay (OPTION)
sha1: F1D3E3FF4184CA83A230C942A87E4C4D608D2A99
options:
  basename: OPTION.BIN
  target_path: assets/JAP1/VIN/OPTION.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP1/screens/options
  src_path: src/screens/options
  asset_path: asm/JAP1/screens/options
  build_path: build/JAP1

  ld_script_path: linkers/JAP1/screens/options.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP1/screens/sym.options.txt
    - configs/JAP1/sym.bodyprog.txt
    - configs/JAP1/sym.main.txt
  reloc_addrs_path:
    - configs/JAP1/screens/rel.options.txt

  undefined_funcs_auto_path: linkers/JAP1/screens/undefined_funcs_auto.options.txt
  undefined_syms_auto_path: linkers/JAP1/screens/undefined_syms_auto.options.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: options
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0xC78, asm, options]
      - [0x5FDC, data, options]
  - [0x6100]
