name: The MAP0_S02 map overlay (MAP0_S02)
sha1: 2572c3f256e7ff6f6b3797cddc499d0e917743e7
options:
  basename: MAP0_S02.BIN
  target_path: assets/VIN/MAP0_S02.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map0_s02
  src_path: src/maps/map0_s02
  build_path: build

  ld_script_path: linkers/maps/map0_s02.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/maps/sym.map0_s02.txt
    - configs/sym.bodyprog.txt
    - configs/sym.main.txt
  reloc_addrs_path:
    - configs/maps/rel.map0_s02.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map0_s02.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map0_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map0_s02
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x1228, .rodata, map0_s02]
      - [0x1278, rodata]
      - [0x12C8, .rodata, map0_s02_msg]
      - [0x16D0, rodata]

      # .text section
      - [0x1778, c, map0_s02]

      # .data section
      - [0x6414, data, map0_s02]
      - [0x67C0, .data, map0_s02_msg]
      - [0x6818, data]
  - [0xA000]
