name: The MAP0_S00 map overlay (MAP0_S00)
sha1: 046b02eef3b2f99aac0ffd5192461904c8838024
options:
  basename: MAP0_S00.BIN
  target_path: assets/VIN/MAP0_S00.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map0_s00
  src_path: src/maps/map0_s00
  build_path: build

  ld_script_path: linkers/maps/map0_s00.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/maps/sym.map0_s00.txt
    - configs/sym.bodyprog.txt
    - configs/sym.main.txt
  reloc_addrs_path:
    - configs/maps/rel.map0_s00.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map0_s00.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map0_s00.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map0_s00
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, .rodata, map0_s00_header]
      - [0x1050, rodata]
      - [0x1328, .rodata, map0_s00]
      - [0x13DC, rodata]
      - [0x1568, .rodata, map0_s00_2]
      - [0x15A4, rodata]
      - [0x1910, .rodata, map0_s00_msg]
      - [0x1F34, rodata]

      # .text section
      - [0x2138, c, map0_s00]
      - [0x9990, c, map0_s00_2]

      # .data section
      - [0x13D44, .data, map0_s00_anim_info]
      - [0x13F64, data, map0_s00]
      - [0x15D98, .data, map0_s00_header]
      - [0x16140, .data, map0_s00_msg]
      - [0x161DC, data]
  - [0x1A600]
