name: The MAP2_S01 map overlay (MAP2_S01)
sha1: 0dfddece8b582d78cdd4898a5b7bddb764c22f0e
options:
  basename: MAP2_S01.BIN
  target_path: assets/VIN/MAP2_S01.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/maps/map2_s01
  src_path: src/maps/map2_s01
  build_path: build

  ld_script_path: linkers/maps/map2_s01.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/maps/sym.map2_s01.txt
  reloc_addrs_path:
    - configs/maps/rel.map2_s01.txt

  undefined_funcs_auto_path: linkers/maps/undefined_funcs_auto.map2_s01.txt
  undefined_syms_auto_path: linkers/maps/undefined_syms_auto.map2_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map2_s01
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1A98, asm, map2_s01]
      - [0x6768, data, map2_s01]
  - [0x8300]
