name: Boot screen overlay (B_KONAMI)
sha1: 33091576CC27EE3B64081EE8DC5A83FAADF1C4F2
options:
  basename: B_KONAMI.BIN
  target_path: assets/JAP2/1ST/B_KONAMI.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP2/screens/b_konami
  src_path: src/screens/b_konami
  asset_path: asm/JAP2/screens/b_konami
  build_path: build/JAP2

  ld_script_path: linkers/JAP2/screens/b_konami.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP2/screens/sym.b_konami.txt
    - configs/JAP2/screens/sym.stream.txt
    - configs/JAP2/sym.bodyprog.txt
    - configs/JAP2/sym.main.txt
  reloc_addrs_path:
    - configs/JAP2/screens/rel.b_konami.txt

  undefined_funcs_auto_path: linkers/JAP2/screens/undefined_funcs_auto.b_konami.txt
  undefined_syms_auto_path: linkers/JAP2/screens/undefined_syms_auto.b_konami.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: b_konami
    type: code
    start: 0
    vram: 0x800CBBD0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x2FC, asm, b_konami]
      - [0x10A4, data, b_konami]
  - [0x1100]