name: Save/Load screen overlay (SAVELOAD)
sha1: 08A0E213F465CA645D2B9F7E9D4339B5BFF6FFD7
options:
  basename: SAVELOAD.BIN
  target_path: assets/JAP2/VIN/SAVELOAD.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP2/screens/saveload
  src_path: src/screens/saveload
  asset_path: asm/JAP2/screens/saveload
  build_path: build/JAP2

  ld_script_path: linkers/JAP2/screens/saveload.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP2/screens/sym.saveload.txt
    - configs/JAP2/sym.bodyprog.txt
    - configs/JAP2/sym.main.txt
  reloc_addrs_path:
    - configs/JAP2/screens/rel.saveload.txt

  undefined_funcs_auto_path: linkers/JAP2/screens/undefined_funcs_auto.saveload.txt
  undefined_syms_auto_path: linkers/JAP2/screens/undefined_syms_auto.saveload.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: saveload
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x900, asm, saveload]
      - [0x5BE0, data, saveload]
  - [0x5F00]
