name: Main Executable (SLPM_861.92)
sha1: 499576C15892799826ABC5B1596858A555E2F3B7
options:
  basename: main
  target_path: rom/JAP2/SLPM_861.92
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP2/main
  src_path: src/main
  build_path: build/JAP2
  

  ld_script_path: linkers/JAP2/main.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]
  
  symbol_addrs_path:
    - configs/JAP2/sym.bodyprog.txt
    - configs/JAP2/sym.main.txt
  reloc_addrs_path:
    - configs/JAP2/rel.main.txt

  undefined_funcs_auto_path: linkers/JAP2/undefined_funcs_auto.main.txt
  undefined_syms_auto_path: linkers/JAP2/undefined_syms_auto.main.txt
  
  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subalign: 4
    subsegments:
      - [0x800, rodata]
      - [0xF70, asm, main]
      - [0xB91C, data, main]
  - [0x14000]
