name: Item description and names overlay for German (ITEM_GER)
sha1: 1a03a92752c29514af3751b787de4dff1e747447
options:
  basename: ITEM_GER.BIN
  target_path: assets/EUR/VIN/ITEM_GER.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/bodyprog/items
  src_path: src/bodyprog/items
  build_path: build/EUR

  ld_script_path: linkers/EUR/items/item_ger.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/items/sym.item_ger.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/items/rel.item_ger.txt

  undefined_funcs_auto_path: linkers/EUR/items/undefined_funcs_auto.item_ger.txt
  undefined_syms_auto_path: linkers/EUR/items/undefined_syms_auto.item_ger.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: item_ger
    type: code
    start: 0
    vram: 0x800C8B68
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, item_ger]
      #- [0x61C, c, item_ger]
      - [0x61C, data, item_ger]
  - [0x1F00]
