name: Item description and names overlay for Spanish (ITEM_SPN)
sha1: e8b81c9c008dcc361f07d251bd6e57268e36d75c
options:
  basename: ITEM_SPN.BIN
  target_path: assets/EUR/VIN/ITEM_SPN.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/bodyprog/items
  src_path: src/bodyprog/items
  build_path: build/EUR

  ld_script_path: linkers/EUR/items/item_spn.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/items/sym.item_spn.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/items/rel.item_spn.txt

  undefined_funcs_auto_path: linkers/EUR/items/undefined_funcs_auto.item_spn.txt
  undefined_syms_auto_path: linkers/EUR/items/undefined_syms_auto.item_spn.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: item_spn
    type: code
    start: 0
    vram: 0x800C8B68
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata, item_spn]
      #- [0x61C, c, item_spn]
      - [0x61C, data, item_spn]
  - [0x2000]
