name: The MAP0_S20 map overlay French (MAP0_S20)
sha1: 600e35e2fa321d752abbc920f060d9abc6aee663
options:
  basename: MAP0_S20.bin
  target_path: assets/EUR/VIN3/MAP0_S20.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map0_s20
  src_path: src/maps/map0_s00
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map0_s20.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.map0_s20.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/sym.main.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map0_s20.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map0_s20.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map0_s20.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map0_s20
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x2180, asm, map0_s00]
  - [0x13d98, data]
- [0x1a600]
