name: The MAP0_S10 map overlay German (MAP0_S10)
sha1: 6F6158723C55B319A893B0462424160EB1CA9200
options:
  basename: MAP0_S10.BIN
  target_path: assets/EUR/VIN/MAP0_S10.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map0_s10
  src_path: src/maps/map0_s10
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map0_s10.ld

  find_file_boundaries: False
  gp_value: 0x81022BB0
  global_vram_start: 0x81011010
  global_vram_end: 0x80210100

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/maps/sym.map0_s10.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/maps/rel.map0_s10.txt

  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map0_s10.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map0_s10.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map0_s10
    type: code
    start: 0
    vram: 0x800CB370
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x2160, asm, map0_s00]
      - [0x13D78, data]
  - [0x1A600]
