name: The MAP0_S40 map overlay Italian (MAP0_S40)
sha1: b39ce2b04c80fa668c5ee253925de7b767a08829
options:
  basename: MAP0_S40.bin
  target_path: assets/EUR/VIN5/MAP0_S40.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map0_s40
  src_path: src/maps/map0_s00
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map0_s40.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/maps/sym.map0_s40.txt, configs/EUR/sym.bodyprog.txt,
    configs/EUR/sym.main.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map0_s40.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map0_s40.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map0_s40.txt
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map0_s40
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x20e0, asm, map0_s00]
  - [0x13cf8, data]
- [0x1a500]
