name: The MAP1_S35 map overlay Spanish (MAP1_S35)
sha1: fd9f99c2a090c5fe60d04f2cb9e5abaae335d7dd
options:
  basename: MAP1_S35.bin
  target_path: assets/EUR/VIN4/MAP1_S35.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map1_s35
  src_path: src/maps/map1_s05
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map1_s35.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map1_s35.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map1_s35.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map1_s35.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map1_s35.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map1_s35
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1598, asm, map1_s05]
  - [0xc444, data]
- [0xf500]
