name: The MAP1_S10 map overlay German (MAP1_S10)
sha1: b98964bfbe66ff7a367a90264a53eb3d8d381669
options:
  basename: MAP1_S10.bin
  target_path: assets/EUR/VIN2/MAP1_S10.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map1_s10
  src_path: src/maps/map1_s00
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map1_s10.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/maps/sym.map1_s10.txt, configs/EUR/sym.bodyprog.txt,
    configs/EUR/sym.main.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map1_s10.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map1_s10.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map1_s10.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map1_s10
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x22e0, asm, map1_s00]
  - [0x10f84, data]
- [0x17e00]
