name: The MAP1_S06 map overlay English (MAP1_S06)
sha1: fca1267741ea692e6bd9e9e59bce8c0197492385
options:
  basename: MAP1_S06.BIN
  target_path: assets/EUR/VIN/MAP1_S06.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map1_s06
  src_path: src/maps/map1_s06
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map1_s06.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/sym.main.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/maps/sym.map1_s06.txt
  reloc_addrs_path:
    - configs/EUR/maps/rel.map1_s06.txt

  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map1_s06.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map1_s06.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map1_s06
    type: code
    start: 0
    vram: 0x800CB370
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x19e4, asm, map1_s06]
      - [0xd760, data]
  - [0x11B00]
