name: The MAP1_S12 map overlay German (MAP1_S12)
sha1: 13bf87a24a7901f789198cc9d723e95550681411
options:
  basename: MAP1_S12.bin
  target_path: assets/EUR/VIN2/MAP1_S12.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map1_s12
  src_path: src/maps/map1_s02
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map1_s12.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map1_s12.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map1_s12.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map1_s12.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map1_s12.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map1_s12
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x2594, asm, map1_s02]
  - [0x158a0, data]
- [0x1c700]
