name: The MAP2_S43 map overlay Italian (MAP2_S43)
sha1: a94c9a6344d77ed25150be0a3bd2b462bdb2b17d
options:
  basename: MAP2_S43.bin
  target_path: assets/EUR/VIN5/MAP2_S43.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map2_s43
  src_path: src/maps/map2_s03
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map2_s43.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map2_s43.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map2_s43.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map2_s43.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map2_s43.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map2_s43
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1368, asm, map2_s03]
  - [0x35a0, data]
- [0x4900]
