name: The MAP2_S23 map overlay French (MAP2_S23)
sha1: ffd80772311e7ddaef8cb47bcba93f31e14f0b3f
options:
  basename: MAP2_S23.bin
  target_path: assets/EUR/VIN3/MAP2_S23.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map2_s23
  src_path: src/maps/map2_s03
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map2_s23.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map2_s23.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map2_s23.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map2_s23.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map2_s23.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map2_s23
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x13ac, asm, map2_s03]
  - [0x35e4, data]
- [0x4a00]
