name: The MAP2_S14 map overlay German (MAP2_S14)
sha1: 1415e6a8e2068abef3c5b78110f21060ad82b655
options:
  basename: MAP2_S14.bin
  target_path: assets/EUR/VIN2/MAP2_S14.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map2_s14
  src_path: src/maps/map2_s04
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map2_s14.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map2_s14.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map2_s14.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map2_s14.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map2_s14.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map2_s14
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x16c4, asm, map2_s04]
  - [0x3da4, data]
- [0x5f00]
