name: The MAP2_S00 map overlay English (MAP2_S00)
sha1: 1f075ec0529e1f8f0c9ce6471890ab763b95ecbc
options:
  basename: MAP2_S00.BIN
  target_path: assets/EUR/VIN/MAP2_S00.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map2_s00
  src_path: src/maps/map2_s00
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map2_s00.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/sym.main.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/maps/sym.map2_s00.txt
  reloc_addrs_path:
    - configs/EUR/maps/rel.map2_s00.txt

  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map2_s00.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map2_s00.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map2_s00
    type: code
    start: 0
    vram: 0x800CB370
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x3f68, asm, map2_s00]
      - [0x25090, data]
  - [0x2C300]
