name: The MAP3_S40 map overlay Italian (MAP3_S40)
sha1: 9be0a7ee49fbad12540a7249ba4269733749bc3e
options:
  basename: MAP3_S40.bin
  target_path: assets/EUR/VIN5/MAP3_S40.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map3_s40
  src_path: src/maps/map3_s00
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map3_s40.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map3_s40.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map3_s40.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map3_s40.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map3_s40.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map3_s40
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1e60, asm, map3_s00]
  - [0x881c, data]
- [0xc900]
