name: The MAP3_S12 map overlay German (MAP3_S12)
sha1: 8363150651c82bc04e0b96dfce50a486acc83431
options:
  basename: MAP3_S12.bin
  target_path: assets/EUR/VIN2/MAP3_S12.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map3_s12
  src_path: src/maps/map3_s02
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map3_s12.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map3_s12.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map3_s12.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map3_s12.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map3_s12.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map3_s12
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x15e0, asm, map3_s02]
  - [0x7f0c, data]
- [0x9c00]
