name: The MAP3_S16 map overlay German (MAP3_S16)
sha1: 482780595c84c4f4e739d6dcce897e7609a49499
options:
  basename: MAP3_S16.bin
  target_path: assets/EUR/VIN2/MAP3_S16.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map3_s16
  src_path: src/maps/map3_s06
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map3_s16.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map3_s16.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map3_s16.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map3_s16.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map3_s16.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map3_s16
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1e30, asm, map3_s00]
  - [0x8710, data]
- [0xcc00]
