name: The MAP3_S46 map overlay Italian (MAP3_S46)
sha1: 9b16de245edd240202b23e1efa80670b6d560e74
options:
  basename: MAP3_S46.bin
  target_path: assets/EUR/VIN5/MAP3_S46.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map3_s46
  src_path: src/maps/map3_s06
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map3_s46.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map3_s46.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map3_s46.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map3_s46.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map3_s46.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map3_s46
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1d48, asm, map3_s00]
  - [0x8628, data]
- [0xcb00]
