name: The MAP3_S05 map overlay English (MAP3_S05)
sha1: 1ee1e9300c877067f53d72d465a7808ff3d8a8a8
options:
  basename: MAP3_S05.BIN
  target_path: assets/EUR/VIN/MAP3_S05.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map3_s05
  src_path: src/maps/map3_s05
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map3_s05.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/sym.main.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/maps/sym.map3_s05.txt
  reloc_addrs_path:
    - configs/EUR/maps/rel.map3_s05.txt

  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map3_s05.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map3_s05.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s05
    type: code
    start: 0
    vram: 0x800CB370
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1fec, asm, map3_s05]
      - [0xf1a8, data]
  - [0x14000]
