name: The MAP4_S13 map overlay German (MAP4_S13)
sha1: cc477b958ac74534ac9c1a75d5920309df6f569d
options:
  basename: MAP4_S13.bin
  target_path: assets/EUR/VIN2/MAP4_S13.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map4_s13
  src_path: src/maps/map4_s03
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map4_s13.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map4_s13.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map4_s13.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map4_s13.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map4_s13.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map4_s13
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1b2c, asm, map4_s03]
  - [0x11238, data]
- [0x17500]
