name: The MAP4_S34 map overlay Spanish (MAP4_S34)
sha1: 705947a39a52f77a18860ffc4c59cbd334be006f
options:
  basename: MAP4_S34.bin
  target_path: assets/EUR/VIN4/MAP4_S34.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map4_s34
  src_path: src/maps/map4_s04
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map4_s34.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map4_s34.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map4_s34.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map4_s34.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map4_s34.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map4_s34
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x26d8, asm, map4_s04]
  - [0x97e4, data]
- [0xda00]
