name: The MAP4_S36 map overlay Spanish (MAP4_S36)
sha1: 322255524bbe3233014e30a2c385b4dbf7a715a6
options:
  basename: MAP4_S36.bin
  target_path: assets/EUR/VIN4/MAP4_S36.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map4_s36
  src_path: src/maps/map4_s06
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map4_s36.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map4_s36.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map4_s36.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map4_s36.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map4_s36.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map4_s36
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x136c, asm, map4_s06]
  - [0x3538, data]
- [0x4000]
