name: The MAP5_S13 map overlay German (MAP5_S13)
sha1: 0dc3f98c93da4914e4aed91b62e08dbf9b50e0ce
options:
  basename: MAP5_S13.bin
  target_path: assets/EUR/VIN2/MAP5_S13.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map5_s13
  src_path: src/maps/map5_s03
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map5_s13.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map5_s13.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map5_s13.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map5_s13.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map5_s13.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map5_s13
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x2454, asm, map5_s03]
  - [0x96e4, data]
- [0xdd00]
