name: The MAP5_S01 map overlay English (MAP5_S01)
sha1: 307a7cf18f7b02f1fab35f45f417442f3a408330
options:
  basename: MAP5_S01.BIN
  target_path: assets/EUR/VIN/MAP5_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map5_s01
  src_path: src/maps/map5_s01
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map5_s01.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/sym.main.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/maps/sym.map5_s01.txt
  reloc_addrs_path:
    - configs/EUR/maps/rel.map5_s01.txt

  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map5_s01.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map5_s01.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map5_s01
    type: code
    start: 0
    vram: 0x800CB370
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x34d0, asm, map5_s01]
      - [0x236c4, data]
  - [0x2AA00]
