name: The MAP5_S43 map overlay Italian (MAP5_S43)
sha1: 8a14d047d47d9ed495e72b71e71c8d52a1c03734
options:
  basename: MAP5_S43.bin
  target_path: assets/EUR/VIN5/MAP5_S43.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map5_s43
  src_path: src/maps/map5_s03
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map5_s43.ld
  find_file_boundaries: false
  gp_value: 2147628724
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map5_s43.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map5_s43.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map5_s43.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map5_s43.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map5_s43
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x23b4, asm, map5_s03]
  - [0x9644, data]
- [0xdc00]
