name: The MAP5_S40 map overlay Italian (MAP5_S40)
sha1: f9d320b26c90f2d183f29160832c4a38db55c182
options:
  basename: MAP5_S40.bin
  target_path: assets/EUR/VIN5/MAP5_S40.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map5_s40
  src_path: src/maps/map5_s00
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map5_s40.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map5_s40.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map5_s40.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map5_s40.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map5_s40.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map5_s40
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1b68, asm, map5_s00]
  - [0xf988, data]
- [0x14f00]
