name: The MAP5_S20 map overlay French (MAP5_S20)
sha1: b34d643d2b44652c3fcd735a7dbbec028aaa5390
options:
  basename: MAP5_S20.bin
  target_path: assets/EUR/VIN3/MAP5_S20.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map5_s20
  src_path: src/maps/map5_s00
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map5_s20.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map5_s20.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map5_s20.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map5_s20.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map5_s20.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map5_s20
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1ba0, asm, map5_s00]
  - [0xf9c0, data]
- [0x14f00]
