name: The MAP6_S22 map overlay French (MAP6_S22)
sha1: 2720bf1735a6e7c02106cdf53e3554c9d513e289
options:
  basename: MAP6_S22.bin
  target_path: assets/EUR/VIN3/MAP6_S22.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map6_s22
  src_path: src/maps/map6_s02
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map6_s22.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map6_s22.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map6_s22.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map6_s22.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map6_s22.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map6_s22
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1650, asm, map6_s02]
  - [0x9f08, data]
- [0xba00]
