name: The MAP6_S30 map overlay Spanish (MAP6_S30)
sha1: d9809e6e38fe60ef015f64f5f74b1f9673bc58e4
options:
  basename: MAP6_S30.bin
  target_path: assets/EUR/VIN4/MAP6_S30.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map6_s30
  src_path: src/maps/map6_s00
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map6_s30.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map6_s30.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map6_s30.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map6_s30.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map6_s30.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map6_s30
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x35e8, asm, map6_s00]
  - [0x23d7c, data]
- [0x2ac00]
