name: The MAP6_S25 map overlay French (MAP6_S25)
sha1: 36133aa2a5907bd894b36fdce4915937f4ae0918
options:
  basename: MAP6_S25.bin
  target_path: assets/EUR/VIN3/MAP6_S25.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map6_s25
  src_path: src/maps/map6_s05
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map6_s25.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map6_s25.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map6_s25.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map6_s25.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map6_s25.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map6_s25
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x1390, asm, map6_s05]
  - [0x36ac, data]
- [0x4100]
