name: The MAP7_S03 map overlay English (MAP7_S03)
sha1: edfd641098f754d0e1633cd0eb6046a0389223ff
options:
  basename: MAP7_S03.BIN
  target_path: assets/EUR/VIN/MAP7_S03.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map7_s03
  src_path: src/maps/map7_s03
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map7_s03.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/sym.main.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/maps/sym.map7_s03.txt
  reloc_addrs_path:
    - configs/EUR/maps/rel.map7_s03.txt

  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map7_s03.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map7_s03.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map7_s03
    type: code
    start: 0
    vram: 0x800CB370
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x3ab0, asm, map7_s03]
      - [0x206ec, data]
  - [0x2B900]
