name: The MAP7_S10 map overlay German (MAP7_S10)
sha1: f7c035441ec904b08172cdc7fed3332edcd9ac5e
options:
  basename: MAP7_S10.bin
  target_path: assets/EUR/VIN2/MAP7_S10.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/maps/map7_s10
  src_path: src/maps/map7_s00
  build_path: build/EUR

  ld_script_path: linkers/EUR/maps/map7_s10.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
  - configs/EUR/maps/sym.main.txt
  - configs/EUR/maps/sym.bodyprog.txt
  - configs/EUR/maps/sym.map7_s10.txt
  reloc_addrs_path:
  - configs/EUR/maps/rel.map7_s10.txt
  
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map7_s10.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map7_s10.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map7_s10
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x2144, asm, map7_s00]
  - [0x962c, data]
- [0xb000]
