name: The MAP7_S41 map overlay Italian (MAP7_S41)
sha1: eea61cf313d4d3e56adf85f3089b50dc0d54adee
options:
  basename: MAP7_S41.bin
  target_path: assets/EUR/VIN5/MAP7_S41.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map7_s41
  src_path: src/maps/map7_s01
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map7_s41.ld
  find_file_boundaries: false
  gp_value: 2147628724
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map7_s41.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map7_s41.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map7_s41.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map7_s41.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map7_s41
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x33dc, asm, map7_s01]
  - [0x159cc, data]
- [0x19f00]
