name: The MAP7_S30 map overlay Spanish (MAP7_S30)
sha1: e397b46975633f8e60cce6c12f54029711c9558a
options:
  basename: MAP7_S30.bin
  target_path: assets/EUR/VIN4/MAP7_S30.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC
  asm_path: asm/EUR/maps/map7_s30
  src_path: src/maps/map7_s00
  build_path: build/EUR
  ld_script_path: linkers/EUR/maps/map7_s30.ld
  find_file_boundaries: false
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000
  o_as_suffix: false
  use_legacy_include_asm: false
  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel
  section_order: [.rodata, .text, .data, .bss]
  symbol_addrs_path: [configs/EUR/sym.main.txt, configs/EUR/sym.bodyprog.txt, configs/EUR/maps/sym.map7_s30.txt]
  reloc_addrs_path: [configs/EUR/maps/rel.map7_s30.txt]
  undefined_funcs_auto_path: linkers/EUR/maps/undefined_funcs_auto.map7_s30.txt
  undefined_syms_auto_path: linkers/EUR/maps/undefined_syms_auto.map7_s30.txt
  extensions_path: tools/splat_ext
  subalign: 4
  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
- name: map7_s30
  type: code
  start: 0
  vram: 0x800CB370
  align: 4
  subalign: 4
  subsegments:
  - [0, rodata]
  - [0x207c, asm, map7_s00]
  - [0x9564, data]
- [0xaf00]
