categories:
  - id: engine
    name: Engine
    paths:
      - bodyprog
  - id: main
    name: Main Executable
    paths:
      - main
  - id: screen
    name: Game Screens
    paths:
      - screens
  - id: map
    name: Map Overlays
    paths:
      - maps

expected_paths:
  asm: expected/asm

ignored_files:
  - main/header
  - main/psyq/libsn/snmain

output: ./objdiff.json
