name: Credits roll overlay (STF_ROLL)
sha1: 5a40c5ea20e9903804c5656c828869f8b858c2d1
options:
  basename: STF_ROLL.BIN
  target_path: assets/USA/VIN/STF_ROLL.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/screens/credits
  src_path: src/screens/credits
  asset_path: asm/USA/screens/credits
  build_path: build/USA/

  ld_script_path: linkers/USA/screens/credits.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/screens/sym.credits.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/USA/screens/rel.credits.txt

  undefined_funcs_auto_path: linkers/USA/screens/undefined_funcs_auto.credits.txt
  undefined_syms_auto_path: linkers/USA/screens/undefined_syms_auto.credits.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: credits
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, pad]
      - [0x8, .rodata, credits]

      # .text section
      - [0x828, c, credits]

      # .data section
      - [0x2F58, .data, credits]

  # Random garbage data at end, define as bin file to make Splat ignore it.
  - name: footer_data
    type: bin
    start: 0x3A10
  - [0x3B00]
