name: Video stream logic overlay (STREAM)
sha1: 2a0ffcbbb4f28d3bb66f7f73f18c1d4502cb2fe6
options:
  basename: STREAM.BIN
  target_path: assets/USA/VIN/STREAM.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/screens/stream
  src_path: src/screens/stream
  asset_path: asm/USA/screens/stream
  build_path: build/USA

  ld_script_path: linkers/USA/screens/stream.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/screens/sym.stream.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/USA/screens/rel.stream.txt

  undefined_funcs_auto_path: linkers/USA/screens/undefined_funcs_auto.stream.txt
  undefined_syms_auto_path: linkers/USA/screens/undefined_syms_auto.stream.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: stream
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, o, ../../lib/libpress/libpress, .rdata]

      # .text section
      - [0x54, c, stream]
      - [0xECC, o, ../../lib/libds/dscb]
      - [0xF2C, o, ../../lib/libpress/libpress]
      - [0x15BC, o, ../../lib/libpress/vlc]

      # .data section
      - [0x193C, .data, stream]
      - [0x195C, o, ../../lib/libpress/libpress, .data]
      - [0x1AAC, o, ../../lib/libpress/vlc, .data]
      - [0x1ADC, o, ../../lib/libpress/table, .data]
      - [0x12ADC, data, stream_801F50DC]

      # .bss section
      - [0x12AE0, .bss, stream]
      - [0x12AE4, pad, garbagebss/stream_801F50E4] # Contains random padding data.
      - [0x12AE8, o, ../../lib/libds/dscb, .bss]

  # Random garbage data at end, overlaps into .bss causing issues, define as seperate segment
  - name: footer_data
    type: bin
    start: 0x12AF4

  - [0x12B00]
