name: The MAP0_S02 map overlay (MAP0_S02)
sha1: 2572c3f256e7ff6f6b3797cddc499d0e917743e7
options:
  basename: MAP0_S02.BIN
  target_path: assets/USA/VIN/MAP0_S02.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map0_s02
  src_path: src/maps/map0_s02
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map0_s02.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/maps/sym.map0_s02.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map0_s02.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map0_s02.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map0_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map0_s02
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map0_s02_header]
      - [0x1050, .rodata, map0_s02]
      - [0x12C8, .rodata, map0_s02_events]

      # .text section
      - [0x1778, c, map0_s02_header]
      - [0x1778, c, map0_s02_events_data]
      - [0x1778, c, map0_s02]
      - [0x5650, c, map0_s02_events]

      # .data section
      - [0x6414, data, map0_s02_anim_info]
      - [0x6500, data]
      - [0x65E4, .data, map0_s02_header]
      - [0x67C0, .data, map0_s02_events]
      - [0x6818, .data, map0_s02_events_data]
      - [0x6974, data]
  - [0xA000]
