name: The MAP1_S02 map overlay (MAP1_S02)
sha1: d1b9b3730b0903413e68dba6d9280f4eb81ea34f
options:
  basename: MAP1_S02.BIN
  target_path: assets/USA/VIN/MAP1_S02.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map1_s02
  src_path: src/maps/map1_s02
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map1_s02.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map1_s02.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map1_s02.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map1_s02.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map1_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map1_s02
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map1_s02_header]
      - [0x1050, .rodata, map1_s02]

      - [0x24D4, c, map1_s02_header]
      - [0x24D4, c, map1_s02_events_data]
      - [0x24D4, c, map1_s02_anim_info]

      # .text section
      - [0x24D4, c, map1_s02]

      # .data section
      - [0x157E0, .data, map1_s02_anim_info]
      - [0x15AF0, data]
      - [0x17cec, .data, map1_s02_header]
      - [0x182DC, .data, map1_s02]
      - [0x183B8, .data, map1_s02_events_data]
      - [0x18964, data]
  - [0x1C600]
