name: The MAP1_S03 map overlay (MAP1_S03)
sha1: 3fe754228375f9f1dd989debb68cd7ab79e5873a
options:
  basename: MAP1_S03.BIN
  target_path: assets/USA/VIN/MAP1_S03.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map1_s03
  src_path: src/maps/map1_s03
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map1_s03.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map1_s03.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map1_s03.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map1_s03.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map1_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map1_s03
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map1_s03_header]
      - [0x1050, .rodata, map1_s03]

      - [0x2768, c, map1_s03_header]
      - [0x2768, c, map1_s03_events_data]
      - [0x2768, c, map1_s03_anim_info]
      # .text section
      - [0x2768, c, map1_s03]

      # .data section
      - [0x15A00, .data, map1_s03_anim_info]
      - [0x15D30, data]
      - [0x17fac, .data, map1_s03_header]
      - [0x18468, .data, map1_s03]
      - [0x18528, .data, map1_s03_events_data]
      - [0x189FC, data]
  - [0x1CF00]
