name: The MAP1_S00 map overlay (MAP1_S00)
sha1: 70a0fb2193cd633bcff30b5ccde55749b0599061
options:
  basename: MAP1_S00.BIN
  target_path: assets/USA/VIN/MAP1_S00.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map1_s00
  src_path: src/maps/map1_s00
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map1_s00.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/maps/sym.map1_s00.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/sym.main.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map1_s00.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map1_s00.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map1_s00.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map1_s00
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map1_s00_header]
      - [0x1050, .rodata, map1_s00]

      - [0x2230, c, map1_s00_header]
      - [0x2230, c, map1_s00_events_data]
      - [0x2230, c, map1_s00_anim_info]

      # .text section
      - [0x2230, c, map1_s00]

      # .data section
      - [0x10ED4, .data, map1_s00_anim_info]
      - [0x110A4, data]
      - [0x13C44, .data, map1_s00]
      - [0x13CE4, .data, map1_s00_events_data]
      - [0x141A0, data]
  - [0x17D00]
