name: The MAP2_S02 map overlay (MAP2_S02)
sha1: 21bbf93766c8903711183c52a6be1b557817cef7
options:
  basename: MAP2_S02.BIN
  target_path: assets/USA/VIN/MAP2_S02.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map2_s02
  src_path: src/maps/map2_s02
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map2_s02.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map2_s02.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map2_s02.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map2_s02.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map2_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map2_s02
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map2_s02_header]
      - [0x1050, .rodata, map2_s02]

      - [0x332C, c, map2_s02_header]
      - [0x332C, c, map2_s02_events_data]
      - [0x332C, c, map2_s02_anim_info]

      # .text section
      - [0x332C, c, map2_s02]

      # .data section
      - [0x21524, .data, map2_s02_anim_info]
      - [0x21734, data]
      - [0x23ecc, .data, map2_s02_header]
      - [0x2411C, .data, map2_s02]
      - [0x24164, .data, map2_s02_events_data]
      - [0x2435C, data]
  - [0x27700]
