name: The MAP2_S03 map overlay (MAP2_S03)
sha1: ccca5fc42275356361c4ed22ecb217ff35573d95
options:
  basename: MAP2_S03.BIN
  target_path: assets/USA/VIN/MAP2_S03.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map2_s03
  src_path: src/maps/map2_s03
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map2_s03.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map2_s03.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map2_s03.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map2_s03.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map2_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map2_s03
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map2_s03_header]
      - [0x1050, .rodata, map2_s03]

      # .text section
      - [0x138C, c, map2_s03_anim_info]
      - [0x138C, c, map2_s03_header]
      - [0x138C, c, map2_s03_events_data]
      - [0x138C, c, map2_s03]

      # .data section
      - [0x35C4, .data, map2_s03_anim_info]
      - [0x3638, data]
      - [0x373c, .data, map2_s03_header]
      - [0x375C, .data, map2_s03]
      - [0x379C, .data, map2_s03_events_data]
      - [0x37B4, data]
  - [0x4A00]
