name: The MAP3_S06 map overlay (MAP3_S06)
sha1: 9fa107d6f4d38c63a1ec691202d323e025ee7ee0
options:
  basename: MAP3_S06.BIN
  target_path: assets/USA/VIN/MAP3_S06.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map3_s06
  src_path: src/maps/map3_s06
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map3_s06.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map3_s06.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map3_s06.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map3_s06.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map3_s06.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s06
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map3_s06_header]
      - [0x1050, .rodata, map3_s06]
      - [0x12D8, .rodata, Chara_Dahlia]
      - [0x139C, rodata]
      - [0x13A0, .rodata, map3_s06_2]
      - [0x1D65, rodata] # 3 random bytes, linker artifact, splat doesn't seem to write to .s so postbuild.py has to patch them back in.

      - [0x1D68, c, map3_s06_header]
      - [0x1D68, c, map3_s06_events_data]
      - [0x1D68, c, map3_s06_anim_info]

      # .text section
      - [0x1D68, c, map3_s06]
      - [0x5B80, c, Chara_Dahlia]
      - [0x6760, c, map3_s06_2]

      # .data section
      - [0x8648, .data, map3_s06_anim_info]
      - [0x86F8, data]
      - [0x8b44, .data, map3_s06_header]
      - [0x8E44, .data, map3_s06_2]
      - [0x8F00, .data, map3_s06_events_data]
      - [0x9158, data]
  - [0xCB00]
