name: The MAP3_S03 map overlay (MAP3_S03)
sha1: a1b10291430d4aacf947c896f28ae52cabb3ad23
options:
  basename: MAP3_S03.BIN
  target_path: assets/USA/VIN/MAP3_S03.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map3_s03
  src_path: src/maps/map3_s03
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map3_s03.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map3_s03.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map3_s03.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map3_s03.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map3_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s03
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map3_s03_header]
      - [0x1050, .rodata, map3_s03]

      - [0x1EE8, c, map3_s03_header]
      - [0x1EE8, c, map3_s03_events_data]
      - [0x1EE8, c, map3_s03_anim_info]

      # .text section
      - [0x1EE8, c, map3_s03]

      # .data section
      - [0xB910, .data, map3_s03_anim_info]
      - [0xBB20, data]
      - [0xCE6C, .data, map3_s03]
      - [0xCF68, .data, map3_s03_events_data]
      - [0xD5C8, data]
  - [0xF000]
