name: The MAP3_S05 map overlay (MAP3_S05)
sha1: 7bb861a62f926249218aded043ed37e3596ab01c
options:
  basename: MAP3_S05.BIN
  target_path: assets/USA/VIN/MAP3_S05.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map3_s05
  src_path: src/maps/map3_s05
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map3_s05.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map3_s05.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map3_s05.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map3_s05.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map3_s05.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s05
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map3_s05_header]
      - [0x1050, .rodata, map3_s05]

      - [0x207C, c, map3_s05_header]
      - [0x207C, c, map3_s05_events_data]
      - [0x207C, c, map3_s05_anim_info]

      # .text section
      - [0x207C, c, map3_s05]

      # .data section
      - [0xFA68, .data, map3_s05_anim_info]
      - [0xFCD8, data]
      - [0x10c74, .data, map3_s05_header]
      - [0x11178, .data, map3_s05]
      - [0x11218, .data, map3_s05_events_data]
      - [0x116F8, data]
  - [0x14000]
