name: The MAP3_S00 map overlay (MAP3_S00)
sha1: 98c307b9e58198d7645d1b41867d03922f1a9649
options:
  basename: MAP3_S00.BIN
  target_path: assets/USA/VIN/MAP3_S00.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map3_s00
  src_path: src/maps/map3_s00
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map3_s00.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map3_s00.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map3_s00.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map3_s00.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map3_s00.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s00
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map3_s00_header]
      - [0x1050, .rodata, map3_s00]
      - [0x12C8, .rodata, Chara_Kaufmann]
      - [0x1394, rodata]
      - [0x1398, .rodata, map3_s00_2]

      - [0x1E90, c, map3_s00_header]
      - [0x1E90, c, map3_s00_events_data]
      - [0x1E90, c, map3_s00_anim_info]

      # .text section
      - [0x1E90, c, map3_s00]
      - [0x5CA4, c, Chara_Kaufmann]
      - [0x690C, c, map3_s00_2]

      # .data section
      - [0x884C, .data, map3_s00_anim_info]
      - [0x88FC, data]
      - [0x8DDC, .data, map3_s00_2]
      - [0x8EAC, .data, map3_s00_events_data]
      - [0x8F78, data]
  - [0xC900]
