name: The MAP3_S04 map overlay (MAP3_S04)
sha1: c67608af87edb04f8017cf977c743b6a134cc0b0
options:
  basename: MAP3_S04.BIN
  target_path: assets/USA/VIN/MAP3_S04.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map3_s04
  src_path: src/maps/map3_s04
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map3_s04.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map3_s04.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map3_s04.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map3_s04.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map3_s04.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s04
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map3_s04_header]
      - [0x1050, .rodata, map3_s04]
      - [0x10EC, rodata]
      - [0x10F0, .rodata, Chara_Lisa]
      - [0x1190, .rodata, map3_s04_2]

      - [0x1E04, c, map3_s04_header]
      - [0x1E04, c, map3_s04_events_data]
      - [0x1E04, c, map3_s04_anim_info]

      # .text section
      - [0x1E04, c, map3_s04]
      - [0x7310, c, Chara_Lisa]
      - [0x7DFC, c, map3_s04_2]

      # .data section
      - [0xAE90, .data, map3_s04_anim_info]
      - [0xB0C0, data]
      - [0xbdf4, .data, map3_s04_header]
      - [0xC0CC, .data, map3_s04_2]
      - [0xC1A8, .data, map3_s04_events_data]
      - [0xC424, data]
  - [0xD900]
