name: The MAP3_S01 map overlay (MAP3_S01)
sha1: 1a32770248cf8ff154b1d19f74b6782b1150fe62
options:
  basename: MAP3_S01.BIN
  target_path: assets/USA/VIN/MAP3_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map3_s01
  src_path: src/maps/map3_s01
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map3_s01.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map3_s01.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map3_s01.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map3_s01.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map3_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s01
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map3_s01_header]
      - [0x1050, .rodata, map3_s01]

      - [0x1C9C, c, map3_s01_header]
      - [0x1C9C, c, map3_s01_events_data]
      - [0x1C9C, c, map3_s01_anim_info]

      # .text section
      - [0x1C9C, c, map3_s01]

      # .data section
      - [0xA494, .data, map3_s01_anim_info]
      - [0xA684, data]
      - [0xB184, .data, map3_s01]
      - [0xB228, .data, map3_s01_events_data]
      - [0xB75C, data]
  - [0xF300]
