name: The MAP4_S01 map overlay (MAP4_S01)
sha1: 57beb1f16bf908d7b83d070190486912628fb006
options:
  basename: MAP4_S01.BIN
  target_path: assets/USA/VIN/MAP4_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map4_s01
  src_path: src/maps/map4_s01
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map4_s01.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map4_s01.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map4_s01.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map4_s01.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map4_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map4_s01
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map4_s01_header]
      - [0x1050, .rodata, map4_s01]
      - [0x13E0, .rodata, Chara_Cybil]
      - [0x14D0, .rodata, map4_s01_2]

      - [0x2C24, c, map4_s01_header]
      - [0x2C24, c, map4_s01_events_data]
      - [0x2C24, c, map4_s01_anim_info]

      # .text section
      - [0x2C24, c, map4_s01]
      - [0x6878, c, Chara_Cybil]
      - [0x7B48, c, map4_s01_2]

      # .data section
      - [0xB93C, .data, map4_s01_anim_info]
      - [0xBB2C, data]
      - [0xC1A0, .data, map4_s01_2]
      - [0xC378, .data, map4_s01_events_data]
      - [0xC4A4, data]
  - [0xEC00]
