name: The MAP4_S02 map overlay (MAP4_S02)
sha1: 4fc3bff65c135b7e6cb4ce7de25267c53441559a
options:
  basename: MAP4_S02.BIN
  target_path: assets/USA/VIN/MAP4_S02.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map4_s02
  src_path: src/maps/map4_s02
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map4_s02.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map4_s02.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map4_s02.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map4_s02.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map4_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map4_s02
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map4_s02_header]
      - [0x1050, .rodata, map4_s02]

      - [0x3290, c, map4_s02_header]
      - [0x3290, c, map4_s02_events_data]
      - [0x3290, c, map4_s02_anim_info]

      # .text section
      - [0x3290, c, map4_s02]

      # .data section
      - [0x214D8, .data, map4_s02_anim_info]
      - [0x21708, data]
      - [0x24150, .data, map4_s02]
      - [0x24194, .data, map4_s02_events_data]
      - [0x24338, data]
  - [0x27F00]
