name: The MAP4_S06 map overlay (MAP4_S06)
sha1: 196faff8845e01f25b1a1b93735e3559e7dac172
options:
  basename: MAP4_S06.BIN
  target_path: assets/USA/VIN/MAP4_S06.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map4_s06
  src_path: src/maps/map4_s06
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map4_s06.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map4_s06.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map4_s06.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map4_s06.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map4_s06.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map4_s06
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map4_s06_header]
      - [0x1050, .rodata, map4_s06]

      - [0x135C, c, map4_s06_header]
      - [0x135C, c, map4_s06_events_data]
      - [0x135C, c, map4_s06_anim_info]

      # .text section
      - [0x135C, c, map4_s06]

      # .data section
      - [0x3528, .data, map4_s06_anim_info]
      - [0x3578, data]
      - [0x361c, .data, map4_s06_header]
      - [0x363c, data]
      - [0x367C, .data, map4_s06_events_data]
      - [0x3688, data]
  - [0x4000]
