name: The MAP5_S01 map overlay (MAP5_S01)
sha1: acd5ad33720b5c896e277b84916d71b29edb5220
options:
  basename: MAP5_S01.BIN
  target_path: assets/USA/VIN/MAP5_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map5_s01
  src_path: src/maps/map5_s01
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map5_s01.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map5_s01.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map5_s01.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map5_s01.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map5_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map5_s01
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map5_s01_header]
      - [0x1050, .rodata, map5_s01]
      - [0x3515, rodata] # 3 random bytes, linker artifact, splat doesn't seem to write to .s so postbuild.py has to patch them back in.

      - [0x3518, c, map5_s01_header]
      - [0x3518, c, map5_s01_events_data]
      - [0x3518, c, map5_s01_anim_info]

      # .text section
      - [0x3518, c, map5_s01]

      # .data section
      - [0x23D6C, .data, map5_s01_anim_info]
      - [0x23F9C, data]
      - [0x26734, .data, map5_s01_header]
      - [0x26980, .data, map5_s01]
      - [0x269D0, .data, map5_s01_events_data]
      - [0x26BE0, data]
  - [0x2AA00]
