name: The MAP5_S02 map overlay (MAP5_S02)
sha1: c51b192cd00d707a47c1a3c81787574d9efbce06
options:
  basename: MAP5_S02.BIN
  target_path: assets/USA/VIN/MAP5_S02.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map5_s02
  src_path: src/maps/map5_s02
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map5_s02.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map5_s02.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map5_s02.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map5_s02.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map5_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map5_s02
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map5_s02_header]
      - [0x1050, .rodata, map5_s02]
      - [0x1490, .rodata, Chara_Kaufmann]
      - [0x155C, rodata]
      - [0x1560, .rodata, map5_s02_2]

      - [0x2154, c, map5_s02_header]
      - [0x2154, c, map5_s02_events_data]
      - [0x2154, c, map5_s02_anim_info]
      
      # .text section
      - [0x2154, c, map5_s02]
      - [0x9930, c, Chara_Kaufmann]
      - [0xA584, c, map5_s02_2]

      # .data section
      - [0xD9C0, .data, map5_s02_anim_info]
      - [0xDC30, data]
      - [0xFD3C, .data, map5_s02_2]
      - [0xFE08, .data, map5_s02_events_data]
      - [0xFF04, data]
  - [0x11500]
