name: The MAP6_S05 map overlay (MAP6_S05)
sha1: 9a280fd758a838ce5d5b854feec162e1cf0b7463
options:
  basename: MAP6_S05.BIN
  target_path: assets/USA/VIN/MAP6_S05.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map6_s05
  src_path: src/maps/map6_s05
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map6_s05.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map6_s05.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map6_s05.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map6_s05.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map6_s05.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map6_s05
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map6_s05_header]
      - [0x1050, .rodata, map6_s05]

      - [0x1370, c, map6_s05_header]
      - [0x1370, c, map6_s05_events_data]
      - [0x1370, c, map6_s05_anim_info]
      
      # .text section
      - [0x1370, c, map6_s05]

      # .data section
      - [0x368C, .data, map6_s05_anim_info]
      - [0x36DC, data]
      - [0x3784, .data, map6_s05_events_data]
      - [0x3790, data]
  - [0x4100]
