name: The MAP6_S03 map overlay (MAP6_S03)
sha1: 8ae6021bb511bf6fa2f0d919443fa07bed69071f
options:
  basename: MAP6_S03.BIN
  target_path: assets/USA/VIN/MAP6_S03.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map6_s03
  src_path: src/maps/map6_s03
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map6_s03.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map6_s03.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map6_s03.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map6_s03.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map6_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map6_s03
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map6_s03_header]
      - [0x1050, .rodata, map6_s03]

      - [0x1CF4, c, map6_s03_header]
      - [0x1CF4, c, map6_s03_events_data]
      - [0x1CF4, c, map6_s03_anim_info]

      # .text section
      - [0x1CF4, c, map6_s03]

      # .data section
      - [0xFDFC, .data, map6_s03_anim_info]
      - [0xFFCC, data]
      - [0x127a4, .data, map6_s03_header]
      - [0x12868, .data, map6_s03]
      - [0x128AC, .data, map6_s03_events_data]
      - [0x1296C, data]
  - [0x16B00]
