name: The MAP6_S01 map overlay (MAP6_S01)
sha1: 9b4d78ca0b255dc2aef2e3aaa72d2f191ca6b13a
options:
  basename: MAP6_S01.BIN
  target_path: assets/USA/VIN/MAP6_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map6_s01
  src_path: src/maps/map6_s01
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map6_s01.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map6_s01.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map6_s01.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map6_s01.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map6_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map6_s01
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map6_s01_header]
      - [0x1050, .rodata, map6_s01]
      - [0x10A0, .rodata, Chara_Cybil]
      - [0x1190, .rodata, Chara_Dahlia]
      - [0x1264, rodata]
      - [0x1268, .rodata, map6_s01_2]
      
      - [0x25E8, c, map6_s01_header]
      - [0x25E8, c, map6_s01_events_data]
      - [0x25E8, c, map6_s01_anim_info]

      # .text section
      - [0x25E8, c, map6_s01]
      - [0x4F84, c, Chara_Cybil]
      - [0x6258, c, Chara_Dahlia]
      - [0x6DE0, c, map6_s01_2]

      # .data section
      - [0x9EF4, .data, map6_s01_anim_info]
      - [0x9FC4, data]
      - [0xA8C0, .data, map6_s01_2]
      - [0xAA2C, .data, map6_s01_events_data]
      - [0xAAF8, data]
  - [0xC100]
