name: The MAP7_S01 map overlay (MAP7_S01)
sha1: 518c208f38e5c58c86773d8a489e9085aa0e770c
options:
  basename: MAP7_S01.BIN
  target_path: assets/USA/VIN/MAP7_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map7_s01
  src_path: src/maps/map7_s01
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map7_s01.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map7_s01.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map7_s01.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map7_s01.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map7_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map7_s01
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map7_s01_header]
      - [0x1050, .rodata, map7_s01]
      - [0x1824, rodata]
      - [0x1828, .rodata, Chara_GhostChildAlessa]
      - [0x1858, .rodata, Chara_Lisa]
      - [0x18F8, .rodata, map7_s01_2]

      - [0x342C, c, map7_s01_header]
      - [0x342C, c, map7_s01_events_data]
      - [0x342C, c, map7_s01_anim_info]
      
      # .text section
      - [0x342C, c, map7_s01]
      - [0xB440, c, Chara_GhostChildAlessa]
      - [0xB884, c, Chara_Lisa]
      - [0xC370, c, Chara_BloodyLisa]
      - [0xC760, c, map7_s01_2]

      # .data section
      - [0x159D0, .data, map7_s01_anim_info]
      - [0x15CA0, data]
      - [0x17468, .data, map7_s01_2]
      - [0x175EC, .data, map7_s01_events_data]
      - [0x17F70, data]
  - [0x19F00]
