name: The MAP7_S02 map overlay (MAP7_S02)
sha1: f340359d9695b64f08a4d0b48ca4da5c816b9a97
options:
  basename: MAP7_S02.BIN
  target_path: assets/USA/VIN/MAP7_S02.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map7_s02
  src_path: src/maps/map7_s02
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map7_s02.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map7_s02.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map7_s02.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map7_s02.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map7_s02.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map7_s02
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map7_s02_header]
      - [0x1050, .rodata, map7_s02]
      - [0x1A30, .rodata, Chara_Lisa]
      - [0x1AD0, .rodata, Chara_Bloodsucker]
      - [0x1AE0, .rodata, Chara_Dahlia]
      - [0x1BA4, rodata]
      - [0x1BA8, .rodata, Chara_GhostChildAlessa]
      - [0x1BD8, .rodata, Chara_Kaufmann]
      - [0x1CA4, rodata]
      - [0x1CA8, .rodata, map7_s02_2]
      - [0x46EC, c, map7_s02_header]
      - [0x46EC, c, map7_s02_events_data]
      - [0x46EC, c, map7_s02_anim_info]

      # .text section
      - [0x46EC, c, map7_s02]
      - [0xC420, c, Chara_Lisa]
      - [0xCF0C, c, Chara_BloodyLisa]
      - [0xD2FC, c, Chara_Bloodsucker]
      - [0xD95C, c, Chara_Dahlia]
      - [0xE4F0, c, Chara_GhostChildAlessa]
      - [0xE934, c, Chara_Kaufmann]
      - [0xF578, c, Chara_GhostDoctor]
      - [0xF6FC, c, map7_s02_2]

      # .data section
      - [0x1C1B8, .data, map7_s02_anim_info]
      - [0x1C4C8, data]
      - [0x1ee14, .data, map7_s02_header]
      - [0x1F92C, .data, map7_s02_2]
      - [0x1FBA8, .data, map7_s02_events_data]
      - [0x2076C, data]
  - [0x22F00]
