name: The MAP7_S03 map overlay (MAP7_S03)
sha1: f6524a4f78b9862a030b931d9f954346ed228231
options:
  basename: MAP7_S03.BIN
  target_path: assets/USA/VIN/MAP7_S03.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map7_s03
  src_path: src/maps/map7_s03
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map7_s03.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map7_s03.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map7_s03.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map7_s03.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map7_s03.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map7_s03
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map7_s03_header]
      - [0x1050, .rodata, map7_s03]
      - [0x1528, .rodata, Chara_Cybil]
      - [0x1618, .rodata, Chara_Dahlia]
      - [0x16EC, rodata]
      - [0x16F0, .rodata, Chara_Alessa]
      - [0x171C, rodata]
      - [0x1720, .rodata, Chara_BloodyIncubator]
      - [0x1750, .rodata, Chara_Kaufmann]
      - [0x181C, rodata]
      - [0x1820, .rodata, map7_s03_2]

      # Data only C files
      - [0x3BF8, c, map7_s03_header]
      - [0x3BF8, c, map7_s03_events_data]
      - [0x3BF8, c, map7_s03_anim_info]

      # .text section
      - [0x3BF8, c, map7_s03]
      - [0x7B20, c, Chara_Cybil]
      - [0x8DF0, c, Chara_Dahlia]
      - [0x9990, c, Chara_Alessa]
      - [0xA10C, c, Chara_BloodyIncubator]
      - [0xA64C, c, Chara_Incubator]
      - [0xA9E0, c, Chara_Kaufmann]
      - [0xB6D8, c, Chara_BloodyLisa]
      - [0xBAC8, c, map7_s03_2]

      # .data section
      - [0x20828, .data, map7_s03_anim_info]
      - [0x20B58, data]
      - [0x23A74, .data, map7_s03_2]
      - [0x23C04, .data, map7_s03_events_data]
      - [0x23CA0, data]
  - [0x2BA00]
