name: The MAP7_S00 map overlay (MAP7_S00)
sha1: 170fdbef21f21993c113924da58ab407c8157d99
options:
  basename: MAP7_S00.BIN
  target_path: assets/USA/VIN/MAP7_S00.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/USA/maps/map7_s00
  src_path: src/maps/map7_s00
  build_path: build/USA

  ld_script_path: linkers/USA/maps/map7_s00.ld

  find_file_boundaries: false
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: false
  use_legacy_include_asm: false

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/USA/sym.main.txt
    - configs/USA/sym.bodyprog.txt
    - configs/USA/maps/sym.map7_s00.txt
  reloc_addrs_path:
    - configs/USA/maps/rel.map7_s00.txt

  undefined_funcs_auto_path: linkers/USA/maps/undefined_funcs_auto.map7_s00.txt
  undefined_syms_auto_path: linkers/USA/maps/undefined_syms_auto.map7_s00.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map7_s00
    type: code
    start: 0
    vram: 0x800C9578
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, rodata]
      - [0x4, .rodata, map7_s00_header]
      - [0x1050, .rodata, map7_s00]
      - [0x14F4, rodata]
      - [0x14F8, .rodata, Chara_Lisa]
      - [0x1598, .rodata, map7_s00_2]

      - [0x20AC, c, map7_s00_header]
      - [0x20AC, c, map7_s00_events_data]
      - [0x20AC, c, map7_s00_anim_info]

      # .text section
      - [0x20AC, c, map7_s00]
      - [0x54C0, c, Chara_Lisa]
      - [0x5FC0, c, map7_s00_2]

      # .data section
      - [0x959C, .data, map7_s00_anim_info]
      - [0x96AC, data]
      - [0x9a14, .data, map7_s00_header]
      - [0x9ABC, .data, map7_s00_2]
      - [0x9B80, .data, map7_s00_events_data]
      - [0x9C1C, data]
  - [0xAF00]
