name: The MAP3_S04 map overlay (MAP3_S04)
sha1: d792dc8e0bce080c9f6ce99fa616b9698ba6d231
options:
  basename: MAP3_S04.BIN
  target_path: assets/JAP1/VIN/MAP3_S04.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP1/maps/map3_s04
  src_path: src/maps/map3_s04
  build_path: build/JAP1

  ld_script_path: linkers/JAP1/maps/map3_s04.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP1/sym.main.txt
    - configs/JAP1/sym.bodyprog.txt
    - configs/JAP1/maps/sym.map3_s04.txt
  reloc_addrs_path:
    - configs/JAP1/maps/rel.map3_s04.txt

  undefined_funcs_auto_path: linkers/JAP1/maps/undefined_funcs_auto.map3_s04.txt
  undefined_syms_auto_path: linkers/JAP1/maps/undefined_syms_auto.map3_s04.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s04
    type: code
    start: 0
    vram: 0x800CBBD0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1d3c, asm, map3_s04]
      - [0xadc4, data]
  - [0xD800]
