name: The MAP4_S01 map overlay (MAP4_S01)
sha1: c4c5292aefd6508e33f8e12c56a3571cae289ab4
options:
  basename: MAP4_S01.BIN
  target_path: assets/JAP1/VIN/MAP4_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP1/maps/map4_s01
  src_path: src/maps/map4_s01
  build_path: build/JAP1

  ld_script_path: linkers/JAP1/maps/map4_s01.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP1/sym.main.txt
    - configs/JAP1/sym.bodyprog.txt
    - configs/JAP1/maps/sym.map4_s01.txt
  reloc_addrs_path:
    - configs/JAP1/maps/rel.map4_s01.txt

  undefined_funcs_auto_path: linkers/JAP1/maps/undefined_funcs_auto.map4_s01.txt
  undefined_syms_auto_path: linkers/JAP1/maps/undefined_syms_auto.map4_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map4_s01
    type: code
    start: 0
    vram: 0x800CBBD0
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x2ACC, asm, map4_s01]
      - [0xb7e4, data]
  - [0xEB00]
