name: Main Game Logic Overlay (BODYPROG)
sha1: a57c3a5aa9aa91df2359fca16086b0b2d0ed86cf
options:
  basename: BODYPROG.BIN
  target_path: assets/JAP1/1ST/BODYPROG.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP1/bodyprog
  src_path: src/bodyprog
  asset_path: asm/JAP1/bodyprog
  build_path: build/JAP1

  ld_script_path: linkers/JAP1/bodyprog.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
   # - configs/JAP1/screens/sym.b_konami.txt - Can't currently be included as function addrs overlap with map overlay data addrs
    - configs/JAP1/screens/sym.stream.txt
    - configs/JAP1/screens/sym.saveload.txt
    - configs/JAP1/screens/sym.options.txt
    - configs/JAP1/screens/sym.credits.txt
    - configs/JAP1/sym.bodyprog.txt
    - configs/JAP1/sym.main.txt
  reloc_addrs_path:
    - configs/JAP1/rel.bodyprog.txt

  undefined_funcs_auto_path: linkers/JAP1/undefined_funcs_auto.bodyprog.txt
  undefined_syms_auto_path: linkers/JAP1/undefined_syms_auto.bodyprog.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: bodyprog
    type: code
    start: 0x0
    vram: 0x80024B60
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x985C, asm, bodyprog]
      - [0x866F8, data, bodyprog]
  - [0xA7100]
