name: Boot screen overlay (B_KONAMI)
sha1: 30CD5A88C6CD266EAB82C034A3C8BC3CC12E686A
options:
  basename: B_KONAMI.BIN
  target_path: assets/JAP0/1ST/B_KONAMI.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP0/screens/b_konami
  src_path: src/screens/b_konami
  asset_path: asm/JAP0/screens/b_konami
  build_path: build/JAP0

  ld_script_path: linkers/JAP0/screens/b_konami.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP0/screens/sym.b_konami.txt
    - configs/JAP0/screens/sym.stream.txt
    - configs/JAP0/sym.bodyprog.txt
    - configs/JAP0/sym.main.txt
  reloc_addrs_path:
    - configs/JAP0/screens/rel.b_konami.txt

  undefined_funcs_auto_path: linkers/JAP0/screens/undefined_funcs_auto.b_konami.txt
  undefined_syms_auto_path: linkers/JAP0/screens/undefined_syms_auto.b_konami.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: b_konami
    type: code
    start: 0
    vram: 0x800CBAA8
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, pad]
      #- [0x8, .rodata, b_konami]
      - [0x8, rodata]

      # .text section
      #- [0x34, c, b_konami]
      - [0x34, asm, b_konami]

      # .data section
      #- [0x10A8, .data, b_konami]
      - [0x10A8, data]

  # Random garbage data at end, define as bin file to make Splat ignore it.
  - name: footer_data
    type: bin
    start: 0x10C8
  - [0x1100]
