name: Options screen overlay (OPTION)
sha1: 518E7B61ADD5602E1C9719B597EAA02CD832B6B6
options:
  basename: OPTION.BIN
  target_path: assets/JAP0/VIN/OPTION.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP0/screens/options
  src_path: src/screens/options
  asset_path: asm/JAP0/screens/options
  build_path: build/JAP0

  ld_script_path: linkers/JAP0/screens/options.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP0/screens/sym.options.txt
    - configs/JAP0/sym.bodyprog.txt
    - configs/JAP0/sym.main.txt
  reloc_addrs_path:
    - configs/JAP0/screens/rel.options.txt

  undefined_funcs_auto_path: linkers/JAP0/screens/undefined_funcs_auto.options.txt
  undefined_syms_auto_path: linkers/JAP0/screens/undefined_syms_auto.options.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: options
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      # .rodata section
      - [0x0, pad]
      #- [0x4, .rodata, options]
      - [0x4, rodata]

      # .text section
      #- [0x10DC, c, options]
      - [0x10DC, asm, options]

      # .data section
      #- [0x5FDC, .data, options]
      - [0x5FDC, data]

  # Random garbage data at end, define as bin file to make Splat ignore it.
  - name: footer_data
    type: bin
    start: 0x60DC
  - [0x6100]