name: The boot screen overlay (B_KONAMI)
sha1: 14829c61f976b261e0b89ee9f967f1be70a54fc6
options:
  basename: B_KONAMI.BIN
  target_path: assets/1ST/B_KONAMI.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/screens/b_konami
  src_path: src/screens/b_konami
  build_path: build

  ld_script_path: linkers/screens/b_konami.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/screens/sym.b_konami.txt
  reloc_addrs_path:
    - configs/screens/rel.b_konami.txt

  undefined_funcs_auto_path: linkers/screens/undefined_funcs_auto.b_konami.txt
  undefined_syms_auto_path: linkers/screens/undefined_syms_auto.b_konami.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: b_konami
    type: code
    start: 0
    vram: 0x800c9578
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x34, asm, b_konami]
      - [0xF78, data, b_konami]
  - [0x1000]
