name: Credits roll overlay (STF_ROLL)
sha1: 5a40c5ea20e9903804c5656c828869f8b858c2d1
options:
  basename: STF_ROLL.BIN
  target_path: assets/VIN/STF_ROLL.BIN
  base_path: ../..
  platform: psx
  compiler: GCC

  asm_path: asm/screens/credits
  src_path: src/screens/credits
  build_path: build/

  ld_script_path: linkers/screens/credits.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/screens/sym.credits.txt
    - configs/sym.bodyprog.txt
    - configs/sym.main.txt
  reloc_addrs_path:
    - configs/screens/rel.credits.txt

  undefined_funcs_auto_path: linkers/screens/undefined_funcs_auto.credits.txt
  undefined_syms_auto_path: linkers/screens/undefined_syms_auto.credits.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: credits
    type: code
    start: 0
    vram: 0x801e2600
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x828, c, credits]
      - [0x2F58, data, credits]
  - [0x3B00]
