name: The MAP3_S01 map overlay (MAP3_S01)
sha1: 59a0bd8c5ecbab227d87f68112c006d7898d9650
options:
  basename: MAP3_S01.BIN
  target_path: assets/JAP0/VIN/MAP3_S01.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/JAP0/maps/map3_s01
  src_path: src/maps/map3_s01
  build_path: build/JAP0

  ld_script_path: linkers/JAP0/maps/map3_s01.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/JAP0/sym.main.txt
    - configs/JAP0/sym.bodyprog.txt
    - configs/JAP0/maps/sym.map3_s01.txt
  reloc_addrs_path:
    - configs/JAP0/maps/rel.map3_s01.txt

  undefined_funcs_auto_path: linkers/JAP0/maps/undefined_funcs_auto.map3_s01.txt
  undefined_syms_auto_path: linkers/JAP0/maps/undefined_syms_auto.map3_s01.txt

  extensions_path: tools/splat_ext

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: map3_s01
    type: code
    start: 0
    vram: 0x800CBAA8
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x1C24, asm, map3_s01]
      - [0x9864, data]
  - [0xF200]
