name: Boot screen overlay (B_KONAMI)
sha1: e2ae3d1f020e99e2929a2d37f900d678a4024131
options:
  basename: B_KONAMI.BIN
  target_path: assets/EUR/1ST/B_KONAMI.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/screens/b_konami
  src_path: src/screens/b_konami
  asset_path: asm/EUR/screens/b_konami
  build_path: build/EUR

  ld_script_path: linkers/EUR/screens/b_konami.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/screens/sym.b_konami.txt
    - configs/EUR/screens/sym.stream.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/screens/rel.b_konami.txt

  undefined_funcs_auto_path: linkers/EUR/screens/undefined_funcs_auto.b_konami.txt
  undefined_syms_auto_path: linkers/EUR/screens/undefined_syms_auto.b_konami.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: b_konami
    type: code
    start: 0
    vram: 0x800CB370
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x34, asm, b_konami]
      - [0xE54, data]
  - [0xF00]
