name: Credits roll overlay (STF_ROLL)
sha1: 945894dd9496923a8bf1915cc619fc9faad71df3
options:
  basename: STF_ROLL.BIN
  target_path: assets/EUR/VIN/STF_ROLL.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/screens/credits
  src_path: src/screens/credits
  asset_path: asm/EUR/screens/credits
  build_path: build/EUR/

  ld_script_path: linkers/EUR/screens/credits.ld

  find_file_boundaries: False
  gp_value: 0x80022BB0
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/screens/sym.credits.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/screens/rel.credits.txt

  undefined_funcs_auto_path: linkers/EUR/screens/undefined_funcs_auto.credits.txt
  undefined_syms_auto_path: linkers/EUR/screens/undefined_syms_auto.credits.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: credits
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x82C, asm, credits]
      - [0x2F60, data]
  - [0x3B00]
