name: Save/Load screen overlay (SAVELOAD)
sha1: 1a5134b617da338e71ef9ac67d270e5a8c128add
options:
  basename: SAVELOAD.BIN
  target_path: assets/EUR/VIN/SAVELOAD.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/screens/saveload
  src_path: src/screens/saveload
  asset_path: asm/EUR/screens/saveload
  build_path: build/EUR

  ld_script_path: linkers/EUR/screens/saveload.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/screens/sym.saveload.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/screens/rel.saveload.txt

  undefined_funcs_auto_path: linkers/EUR/screens/undefined_funcs_auto.saveload.txt
  undefined_syms_auto_path: linkers/EUR/screens/undefined_syms_auto.saveload.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: saveload
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x78C, asm, saveload]
      - [0x4F10, data]
  - [0x5200]
