name: Video stream logic overlay (STREAM)
sha1: 729d19492d86e6e784cabe84c1cf168657f533c4
options:
  basename: STREAM.BIN
  target_path: assets/EUR/VIN/STREAM.BIN
  base_path: ../../..
  platform: psx
  compiler: GCC

  asm_path: asm/EUR/screens/stream
  src_path: src/screens/stream
  asset_path: asm/EUR/screens/stream
  build_path: build/EUR

  ld_script_path: linkers/EUR/screens/stream.ld

  find_file_boundaries: False
  gp_value: 0x800236B4
  global_vram_start: 0x80010000
  global_vram_end: 0x80200000

  o_as_suffix: False
  use_legacy_include_asm: False

  asm_function_macro: glabel
  asm_jtbl_label_macro: jlabel
  asm_data_macro: dlabel

  section_order: [".rodata", ".text", ".data", ".bss"]

  symbol_addrs_path:
    - configs/EUR/screens/sym.stream.txt
    - configs/EUR/sym.bodyprog.txt
    - configs/EUR/sym.main.txt
  reloc_addrs_path:
    - configs/EUR/screens/rel.stream.txt

  undefined_funcs_auto_path: linkers/EUR/screens/undefined_funcs_auto.stream.txt
  undefined_syms_auto_path: linkers/EUR/screens/undefined_syms_auto.stream.txt

  subalign: 4

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
segments:
  - name: stream
    type: code
    start: 0
    vram: 0x801E2600
    align: 4
    subalign: 4
    subsegments:
      - [0x0, rodata]
      - [0x34, asm, stream]
      - [0x193C, data]
  - [0x12B00]
